// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vision_detection.proto

#ifndef PROTOBUF_vision_5fdetection_2eproto__INCLUDED
#define PROTOBUF_vision_5fdetection_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class Vision_DetectionBall;
class Vision_DetectionBallDefaultTypeInternal;
extern Vision_DetectionBallDefaultTypeInternal _Vision_DetectionBall_default_instance_;
class Vision_DetectionFrame;
class Vision_DetectionFrameDefaultTypeInternal;
extern Vision_DetectionFrameDefaultTypeInternal _Vision_DetectionFrame_default_instance_;
class Vision_DetectionRobot;
class Vision_DetectionRobotDefaultTypeInternal;
extern Vision_DetectionRobotDefaultTypeInternal _Vision_DetectionRobot_default_instance_;

namespace protobuf_vision_5fdetection_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_vision_5fdetection_2eproto

// ===================================================================

class Vision_DetectionBall : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Vision_DetectionBall) */ {
 public:
  Vision_DetectionBall();
  virtual ~Vision_DetectionBall();

  Vision_DetectionBall(const Vision_DetectionBall& from);

  inline Vision_DetectionBall& operator=(const Vision_DetectionBall& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Vision_DetectionBall& default_instance();

  static inline const Vision_DetectionBall* internal_default_instance() {
    return reinterpret_cast<const Vision_DetectionBall*>(
               &_Vision_DetectionBall_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Vision_DetectionBall* other);

  // implements Message ----------------------------------------------

  inline Vision_DetectionBall* New() const PROTOBUF_FINAL { return New(NULL); }

  Vision_DetectionBall* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Vision_DetectionBall& from);
  void MergeFrom(const Vision_DetectionBall& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Vision_DetectionBall* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float vel_x = 1;
  bool has_vel_x() const;
  void clear_vel_x();
  static const int kVelXFieldNumber = 1;
  float vel_x() const;
  void set_vel_x(float value);

  // optional float vel_y = 2;
  bool has_vel_y() const;
  void clear_vel_y();
  static const int kVelYFieldNumber = 2;
  float vel_y() const;
  void set_vel_y(float value);

  // optional uint32 area = 3;
  bool has_area() const;
  void clear_area();
  static const int kAreaFieldNumber = 3;
  ::google::protobuf::uint32 area() const;
  void set_area(::google::protobuf::uint32 value);

  // required float x = 4;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 4;
  float x() const;
  void set_x(float value);

  // required float y = 5;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 5;
  float y() const;
  void set_y(float value);

  // optional float height = 6;
  bool has_height() const;
  void clear_height();
  static const int kHeightFieldNumber = 6;
  float height() const;
  void set_height(float value);

  // optional uint32 ball_state = 7;
  bool has_ball_state() const;
  void clear_ball_state();
  static const int kBallStateFieldNumber = 7;
  ::google::protobuf::uint32 ball_state() const;
  void set_ball_state(::google::protobuf::uint32 value);

  // optional uint32 last_touch = 8;
  bool has_last_touch() const;
  void clear_last_touch();
  static const int kLastTouchFieldNumber = 8;
  ::google::protobuf::uint32 last_touch() const;
  void set_last_touch(::google::protobuf::uint32 value);

  // required bool valid = 9;
  bool has_valid() const;
  void clear_valid();
  static const int kValidFieldNumber = 9;
  bool valid() const;
  void set_valid(bool value);

  // required float raw_x = 10;
  bool has_raw_x() const;
  void clear_raw_x();
  static const int kRawXFieldNumber = 10;
  float raw_x() const;
  void set_raw_x(float value);

  // required float raw_y = 11;
  bool has_raw_y() const;
  void clear_raw_y();
  static const int kRawYFieldNumber = 11;
  float raw_y() const;
  void set_raw_y(float value);

  // optional float chip_predict_x = 12;
  bool has_chip_predict_x() const;
  void clear_chip_predict_x();
  static const int kChipPredictXFieldNumber = 12;
  float chip_predict_x() const;
  void set_chip_predict_x(float value);

  // optional float chip_predict_y = 13;
  bool has_chip_predict_y() const;
  void clear_chip_predict_y();
  static const int kChipPredictYFieldNumber = 13;
  float chip_predict_y() const;
  void set_chip_predict_y(float value);

  // @@protoc_insertion_point(class_scope:Vision_DetectionBall)
 private:
  void set_has_vel_x();
  void clear_has_vel_x();
  void set_has_vel_y();
  void clear_has_vel_y();
  void set_has_area();
  void clear_has_area();
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_height();
  void clear_has_height();
  void set_has_ball_state();
  void clear_has_ball_state();
  void set_has_last_touch();
  void clear_has_last_touch();
  void set_has_valid();
  void clear_has_valid();
  void set_has_raw_x();
  void clear_has_raw_x();
  void set_has_raw_y();
  void clear_has_raw_y();
  void set_has_chip_predict_x();
  void clear_has_chip_predict_x();
  void set_has_chip_predict_y();
  void clear_has_chip_predict_y();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  float vel_x_;
  float vel_y_;
  ::google::protobuf::uint32 area_;
  float x_;
  float y_;
  float height_;
  ::google::protobuf::uint32 ball_state_;
  ::google::protobuf::uint32 last_touch_;
  bool valid_;
  float raw_x_;
  float raw_y_;
  float chip_predict_x_;
  float chip_predict_y_;
  friend struct protobuf_vision_5fdetection_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Vision_DetectionRobot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Vision_DetectionRobot) */ {
 public:
  Vision_DetectionRobot();
  virtual ~Vision_DetectionRobot();

  Vision_DetectionRobot(const Vision_DetectionRobot& from);

  inline Vision_DetectionRobot& operator=(const Vision_DetectionRobot& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Vision_DetectionRobot& default_instance();

  static inline const Vision_DetectionRobot* internal_default_instance() {
    return reinterpret_cast<const Vision_DetectionRobot*>(
               &_Vision_DetectionRobot_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Vision_DetectionRobot* other);

  // implements Message ----------------------------------------------

  inline Vision_DetectionRobot* New() const PROTOBUF_FINAL { return New(NULL); }

  Vision_DetectionRobot* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Vision_DetectionRobot& from);
  void MergeFrom(const Vision_DetectionRobot& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Vision_DetectionRobot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool valid = 1;
  bool has_valid() const;
  void clear_valid();
  static const int kValidFieldNumber = 1;
  bool valid() const;
  void set_valid(bool value);

  // optional uint32 robot_id = 2;
  bool has_robot_id() const;
  void clear_robot_id();
  static const int kRobotIdFieldNumber = 2;
  ::google::protobuf::uint32 robot_id() const;
  void set_robot_id(::google::protobuf::uint32 value);

  // required float x = 3;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 3;
  float x() const;
  void set_x(float value);

  // required float y = 4;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 4;
  float y() const;
  void set_y(float value);

  // optional float orientation = 5;
  bool has_orientation() const;
  void clear_orientation();
  static const int kOrientationFieldNumber = 5;
  float orientation() const;
  void set_orientation(float value);

  // optional float vel_x = 6;
  bool has_vel_x() const;
  void clear_vel_x();
  static const int kVelXFieldNumber = 6;
  float vel_x() const;
  void set_vel_x(float value);

  // optional float vel_y = 7;
  bool has_vel_y() const;
  void clear_vel_y();
  static const int kVelYFieldNumber = 7;
  float vel_y() const;
  void set_vel_y(float value);

  // optional float rotate_vel = 8;
  bool has_rotate_vel() const;
  void clear_rotate_vel();
  static const int kRotateVelFieldNumber = 8;
  float rotate_vel() const;
  void set_rotate_vel(float value);

  // optional float accelerate_x = 9;
  bool has_accelerate_x() const;
  void clear_accelerate_x();
  static const int kAccelerateXFieldNumber = 9;
  float accelerate_x() const;
  void set_accelerate_x(float value);

  // optional float accelerate_y = 10;
  bool has_accelerate_y() const;
  void clear_accelerate_y();
  static const int kAccelerateYFieldNumber = 10;
  float accelerate_y() const;
  void set_accelerate_y(float value);

  // required float raw_x = 11;
  bool has_raw_x() const;
  void clear_raw_x();
  static const int kRawXFieldNumber = 11;
  float raw_x() const;
  void set_raw_x(float value);

  // required float raw_y = 12;
  bool has_raw_y() const;
  void clear_raw_y();
  static const int kRawYFieldNumber = 12;
  float raw_y() const;
  void set_raw_y(float value);

  // optional float raw_orientation = 13;
  bool has_raw_orientation() const;
  void clear_raw_orientation();
  static const int kRawOrientationFieldNumber = 13;
  float raw_orientation() const;
  void set_raw_orientation(float value);

  // optional float raw_vel_x = 14;
  bool has_raw_vel_x() const;
  void clear_raw_vel_x();
  static const int kRawVelXFieldNumber = 14;
  float raw_vel_x() const;
  void set_raw_vel_x(float value);

  // optional float raw_vel_y = 15;
  bool has_raw_vel_y() const;
  void clear_raw_vel_y();
  static const int kRawVelYFieldNumber = 15;
  float raw_vel_y() const;
  void set_raw_vel_y(float value);

  // optional float raw_rotate_vel = 16;
  bool has_raw_rotate_vel() const;
  void clear_raw_rotate_vel();
  static const int kRawRotateVelFieldNumber = 16;
  float raw_rotate_vel() const;
  void set_raw_rotate_vel(float value);

  // required float confidence = 17;
  bool has_confidence() const;
  void clear_confidence();
  static const int kConfidenceFieldNumber = 17;
  float confidence() const;
  void set_confidence(float value);

  // @@protoc_insertion_point(class_scope:Vision_DetectionRobot)
 private:
  void set_has_valid();
  void clear_has_valid();
  void set_has_robot_id();
  void clear_has_robot_id();
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_orientation();
  void clear_has_orientation();
  void set_has_vel_x();
  void clear_has_vel_x();
  void set_has_vel_y();
  void clear_has_vel_y();
  void set_has_rotate_vel();
  void clear_has_rotate_vel();
  void set_has_accelerate_x();
  void clear_has_accelerate_x();
  void set_has_accelerate_y();
  void clear_has_accelerate_y();
  void set_has_raw_x();
  void clear_has_raw_x();
  void set_has_raw_y();
  void clear_has_raw_y();
  void set_has_raw_orientation();
  void clear_has_raw_orientation();
  void set_has_raw_vel_x();
  void clear_has_raw_vel_x();
  void set_has_raw_vel_y();
  void clear_has_raw_vel_y();
  void set_has_raw_rotate_vel();
  void clear_has_raw_rotate_vel();
  void set_has_confidence();
  void clear_has_confidence();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  bool valid_;
  ::google::protobuf::uint32 robot_id_;
  float x_;
  float y_;
  float orientation_;
  float vel_x_;
  float vel_y_;
  float rotate_vel_;
  float accelerate_x_;
  float accelerate_y_;
  float raw_x_;
  float raw_y_;
  float raw_orientation_;
  float raw_vel_x_;
  float raw_vel_y_;
  float raw_rotate_vel_;
  float confidence_;
  friend struct protobuf_vision_5fdetection_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Vision_DetectionFrame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Vision_DetectionFrame) */ {
 public:
  Vision_DetectionFrame();
  virtual ~Vision_DetectionFrame();

  Vision_DetectionFrame(const Vision_DetectionFrame& from);

  inline Vision_DetectionFrame& operator=(const Vision_DetectionFrame& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Vision_DetectionFrame& default_instance();

  static inline const Vision_DetectionFrame* internal_default_instance() {
    return reinterpret_cast<const Vision_DetectionFrame*>(
               &_Vision_DetectionFrame_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Vision_DetectionFrame* other);

  // implements Message ----------------------------------------------

  inline Vision_DetectionFrame* New() const PROTOBUF_FINAL { return New(NULL); }

  Vision_DetectionFrame* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Vision_DetectionFrame& from);
  void MergeFrom(const Vision_DetectionFrame& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Vision_DetectionFrame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Vision_DetectionRobot robots_yellow = 2;
  int robots_yellow_size() const;
  void clear_robots_yellow();
  static const int kRobotsYellowFieldNumber = 2;
  const ::Vision_DetectionRobot& robots_yellow(int index) const;
  ::Vision_DetectionRobot* mutable_robots_yellow(int index);
  ::Vision_DetectionRobot* add_robots_yellow();
  ::google::protobuf::RepeatedPtrField< ::Vision_DetectionRobot >*
      mutable_robots_yellow();
  const ::google::protobuf::RepeatedPtrField< ::Vision_DetectionRobot >&
      robots_yellow() const;

  // repeated .Vision_DetectionRobot robots_blue = 3;
  int robots_blue_size() const;
  void clear_robots_blue();
  static const int kRobotsBlueFieldNumber = 3;
  const ::Vision_DetectionRobot& robots_blue(int index) const;
  ::Vision_DetectionRobot* mutable_robots_blue(int index);
  ::Vision_DetectionRobot* add_robots_blue();
  ::google::protobuf::RepeatedPtrField< ::Vision_DetectionRobot >*
      mutable_robots_blue();
  const ::google::protobuf::RepeatedPtrField< ::Vision_DetectionRobot >&
      robots_blue() const;

  // required .Vision_DetectionBall balls = 1;
  bool has_balls() const;
  void clear_balls();
  static const int kBallsFieldNumber = 1;
  const ::Vision_DetectionBall& balls() const;
  ::Vision_DetectionBall* mutable_balls();
  ::Vision_DetectionBall* release_balls();
  void set_allocated_balls(::Vision_DetectionBall* balls);

  // @@protoc_insertion_point(class_scope:Vision_DetectionFrame)
 private:
  void set_has_balls();
  void clear_has_balls();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Vision_DetectionRobot > robots_yellow_;
  ::google::protobuf::RepeatedPtrField< ::Vision_DetectionRobot > robots_blue_;
  ::Vision_DetectionBall* balls_;
  friend struct protobuf_vision_5fdetection_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Vision_DetectionBall

// optional float vel_x = 1;
inline bool Vision_DetectionBall::has_vel_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vision_DetectionBall::set_has_vel_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vision_DetectionBall::clear_has_vel_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vision_DetectionBall::clear_vel_x() {
  vel_x_ = 0;
  clear_has_vel_x();
}
inline float Vision_DetectionBall::vel_x() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionBall.vel_x)
  return vel_x_;
}
inline void Vision_DetectionBall::set_vel_x(float value) {
  set_has_vel_x();
  vel_x_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionBall.vel_x)
}

// optional float vel_y = 2;
inline bool Vision_DetectionBall::has_vel_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Vision_DetectionBall::set_has_vel_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Vision_DetectionBall::clear_has_vel_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Vision_DetectionBall::clear_vel_y() {
  vel_y_ = 0;
  clear_has_vel_y();
}
inline float Vision_DetectionBall::vel_y() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionBall.vel_y)
  return vel_y_;
}
inline void Vision_DetectionBall::set_vel_y(float value) {
  set_has_vel_y();
  vel_y_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionBall.vel_y)
}

// optional uint32 area = 3;
inline bool Vision_DetectionBall::has_area() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Vision_DetectionBall::set_has_area() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Vision_DetectionBall::clear_has_area() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Vision_DetectionBall::clear_area() {
  area_ = 0u;
  clear_has_area();
}
inline ::google::protobuf::uint32 Vision_DetectionBall::area() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionBall.area)
  return area_;
}
inline void Vision_DetectionBall::set_area(::google::protobuf::uint32 value) {
  set_has_area();
  area_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionBall.area)
}

// required float x = 4;
inline bool Vision_DetectionBall::has_x() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Vision_DetectionBall::set_has_x() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Vision_DetectionBall::clear_has_x() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Vision_DetectionBall::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Vision_DetectionBall::x() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionBall.x)
  return x_;
}
inline void Vision_DetectionBall::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionBall.x)
}

// required float y = 5;
inline bool Vision_DetectionBall::has_y() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Vision_DetectionBall::set_has_y() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Vision_DetectionBall::clear_has_y() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Vision_DetectionBall::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Vision_DetectionBall::y() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionBall.y)
  return y_;
}
inline void Vision_DetectionBall::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionBall.y)
}

// optional float height = 6;
inline bool Vision_DetectionBall::has_height() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Vision_DetectionBall::set_has_height() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Vision_DetectionBall::clear_has_height() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Vision_DetectionBall::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline float Vision_DetectionBall::height() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionBall.height)
  return height_;
}
inline void Vision_DetectionBall::set_height(float value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionBall.height)
}

// optional uint32 ball_state = 7;
inline bool Vision_DetectionBall::has_ball_state() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Vision_DetectionBall::set_has_ball_state() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Vision_DetectionBall::clear_has_ball_state() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Vision_DetectionBall::clear_ball_state() {
  ball_state_ = 0u;
  clear_has_ball_state();
}
inline ::google::protobuf::uint32 Vision_DetectionBall::ball_state() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionBall.ball_state)
  return ball_state_;
}
inline void Vision_DetectionBall::set_ball_state(::google::protobuf::uint32 value) {
  set_has_ball_state();
  ball_state_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionBall.ball_state)
}

// optional uint32 last_touch = 8;
inline bool Vision_DetectionBall::has_last_touch() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Vision_DetectionBall::set_has_last_touch() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Vision_DetectionBall::clear_has_last_touch() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Vision_DetectionBall::clear_last_touch() {
  last_touch_ = 0u;
  clear_has_last_touch();
}
inline ::google::protobuf::uint32 Vision_DetectionBall::last_touch() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionBall.last_touch)
  return last_touch_;
}
inline void Vision_DetectionBall::set_last_touch(::google::protobuf::uint32 value) {
  set_has_last_touch();
  last_touch_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionBall.last_touch)
}

// required bool valid = 9;
inline bool Vision_DetectionBall::has_valid() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Vision_DetectionBall::set_has_valid() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Vision_DetectionBall::clear_has_valid() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Vision_DetectionBall::clear_valid() {
  valid_ = false;
  clear_has_valid();
}
inline bool Vision_DetectionBall::valid() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionBall.valid)
  return valid_;
}
inline void Vision_DetectionBall::set_valid(bool value) {
  set_has_valid();
  valid_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionBall.valid)
}

// required float raw_x = 10;
inline bool Vision_DetectionBall::has_raw_x() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Vision_DetectionBall::set_has_raw_x() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Vision_DetectionBall::clear_has_raw_x() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Vision_DetectionBall::clear_raw_x() {
  raw_x_ = 0;
  clear_has_raw_x();
}
inline float Vision_DetectionBall::raw_x() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionBall.raw_x)
  return raw_x_;
}
inline void Vision_DetectionBall::set_raw_x(float value) {
  set_has_raw_x();
  raw_x_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionBall.raw_x)
}

// required float raw_y = 11;
inline bool Vision_DetectionBall::has_raw_y() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Vision_DetectionBall::set_has_raw_y() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Vision_DetectionBall::clear_has_raw_y() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Vision_DetectionBall::clear_raw_y() {
  raw_y_ = 0;
  clear_has_raw_y();
}
inline float Vision_DetectionBall::raw_y() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionBall.raw_y)
  return raw_y_;
}
inline void Vision_DetectionBall::set_raw_y(float value) {
  set_has_raw_y();
  raw_y_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionBall.raw_y)
}

// optional float chip_predict_x = 12;
inline bool Vision_DetectionBall::has_chip_predict_x() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Vision_DetectionBall::set_has_chip_predict_x() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Vision_DetectionBall::clear_has_chip_predict_x() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Vision_DetectionBall::clear_chip_predict_x() {
  chip_predict_x_ = 0;
  clear_has_chip_predict_x();
}
inline float Vision_DetectionBall::chip_predict_x() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionBall.chip_predict_x)
  return chip_predict_x_;
}
inline void Vision_DetectionBall::set_chip_predict_x(float value) {
  set_has_chip_predict_x();
  chip_predict_x_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionBall.chip_predict_x)
}

// optional float chip_predict_y = 13;
inline bool Vision_DetectionBall::has_chip_predict_y() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void Vision_DetectionBall::set_has_chip_predict_y() {
  _has_bits_[0] |= 0x00001000u;
}
inline void Vision_DetectionBall::clear_has_chip_predict_y() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void Vision_DetectionBall::clear_chip_predict_y() {
  chip_predict_y_ = 0;
  clear_has_chip_predict_y();
}
inline float Vision_DetectionBall::chip_predict_y() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionBall.chip_predict_y)
  return chip_predict_y_;
}
inline void Vision_DetectionBall::set_chip_predict_y(float value) {
  set_has_chip_predict_y();
  chip_predict_y_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionBall.chip_predict_y)
}

// -------------------------------------------------------------------

// Vision_DetectionRobot

// required bool valid = 1;
inline bool Vision_DetectionRobot::has_valid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vision_DetectionRobot::set_has_valid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vision_DetectionRobot::clear_has_valid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vision_DetectionRobot::clear_valid() {
  valid_ = false;
  clear_has_valid();
}
inline bool Vision_DetectionRobot::valid() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.valid)
  return valid_;
}
inline void Vision_DetectionRobot::set_valid(bool value) {
  set_has_valid();
  valid_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.valid)
}

// optional uint32 robot_id = 2;
inline bool Vision_DetectionRobot::has_robot_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Vision_DetectionRobot::set_has_robot_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Vision_DetectionRobot::clear_has_robot_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Vision_DetectionRobot::clear_robot_id() {
  robot_id_ = 0u;
  clear_has_robot_id();
}
inline ::google::protobuf::uint32 Vision_DetectionRobot::robot_id() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.robot_id)
  return robot_id_;
}
inline void Vision_DetectionRobot::set_robot_id(::google::protobuf::uint32 value) {
  set_has_robot_id();
  robot_id_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.robot_id)
}

// required float x = 3;
inline bool Vision_DetectionRobot::has_x() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Vision_DetectionRobot::set_has_x() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Vision_DetectionRobot::clear_has_x() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Vision_DetectionRobot::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Vision_DetectionRobot::x() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.x)
  return x_;
}
inline void Vision_DetectionRobot::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.x)
}

// required float y = 4;
inline bool Vision_DetectionRobot::has_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Vision_DetectionRobot::set_has_y() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Vision_DetectionRobot::clear_has_y() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Vision_DetectionRobot::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Vision_DetectionRobot::y() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.y)
  return y_;
}
inline void Vision_DetectionRobot::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.y)
}

// optional float orientation = 5;
inline bool Vision_DetectionRobot::has_orientation() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Vision_DetectionRobot::set_has_orientation() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Vision_DetectionRobot::clear_has_orientation() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Vision_DetectionRobot::clear_orientation() {
  orientation_ = 0;
  clear_has_orientation();
}
inline float Vision_DetectionRobot::orientation() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.orientation)
  return orientation_;
}
inline void Vision_DetectionRobot::set_orientation(float value) {
  set_has_orientation();
  orientation_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.orientation)
}

// optional float vel_x = 6;
inline bool Vision_DetectionRobot::has_vel_x() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Vision_DetectionRobot::set_has_vel_x() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Vision_DetectionRobot::clear_has_vel_x() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Vision_DetectionRobot::clear_vel_x() {
  vel_x_ = 0;
  clear_has_vel_x();
}
inline float Vision_DetectionRobot::vel_x() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.vel_x)
  return vel_x_;
}
inline void Vision_DetectionRobot::set_vel_x(float value) {
  set_has_vel_x();
  vel_x_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.vel_x)
}

// optional float vel_y = 7;
inline bool Vision_DetectionRobot::has_vel_y() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Vision_DetectionRobot::set_has_vel_y() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Vision_DetectionRobot::clear_has_vel_y() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Vision_DetectionRobot::clear_vel_y() {
  vel_y_ = 0;
  clear_has_vel_y();
}
inline float Vision_DetectionRobot::vel_y() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.vel_y)
  return vel_y_;
}
inline void Vision_DetectionRobot::set_vel_y(float value) {
  set_has_vel_y();
  vel_y_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.vel_y)
}

// optional float rotate_vel = 8;
inline bool Vision_DetectionRobot::has_rotate_vel() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Vision_DetectionRobot::set_has_rotate_vel() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Vision_DetectionRobot::clear_has_rotate_vel() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Vision_DetectionRobot::clear_rotate_vel() {
  rotate_vel_ = 0;
  clear_has_rotate_vel();
}
inline float Vision_DetectionRobot::rotate_vel() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.rotate_vel)
  return rotate_vel_;
}
inline void Vision_DetectionRobot::set_rotate_vel(float value) {
  set_has_rotate_vel();
  rotate_vel_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.rotate_vel)
}

// optional float accelerate_x = 9;
inline bool Vision_DetectionRobot::has_accelerate_x() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Vision_DetectionRobot::set_has_accelerate_x() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Vision_DetectionRobot::clear_has_accelerate_x() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Vision_DetectionRobot::clear_accelerate_x() {
  accelerate_x_ = 0;
  clear_has_accelerate_x();
}
inline float Vision_DetectionRobot::accelerate_x() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.accelerate_x)
  return accelerate_x_;
}
inline void Vision_DetectionRobot::set_accelerate_x(float value) {
  set_has_accelerate_x();
  accelerate_x_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.accelerate_x)
}

// optional float accelerate_y = 10;
inline bool Vision_DetectionRobot::has_accelerate_y() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Vision_DetectionRobot::set_has_accelerate_y() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Vision_DetectionRobot::clear_has_accelerate_y() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Vision_DetectionRobot::clear_accelerate_y() {
  accelerate_y_ = 0;
  clear_has_accelerate_y();
}
inline float Vision_DetectionRobot::accelerate_y() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.accelerate_y)
  return accelerate_y_;
}
inline void Vision_DetectionRobot::set_accelerate_y(float value) {
  set_has_accelerate_y();
  accelerate_y_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.accelerate_y)
}

// required float raw_x = 11;
inline bool Vision_DetectionRobot::has_raw_x() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Vision_DetectionRobot::set_has_raw_x() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Vision_DetectionRobot::clear_has_raw_x() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Vision_DetectionRobot::clear_raw_x() {
  raw_x_ = 0;
  clear_has_raw_x();
}
inline float Vision_DetectionRobot::raw_x() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.raw_x)
  return raw_x_;
}
inline void Vision_DetectionRobot::set_raw_x(float value) {
  set_has_raw_x();
  raw_x_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.raw_x)
}

// required float raw_y = 12;
inline bool Vision_DetectionRobot::has_raw_y() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Vision_DetectionRobot::set_has_raw_y() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Vision_DetectionRobot::clear_has_raw_y() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Vision_DetectionRobot::clear_raw_y() {
  raw_y_ = 0;
  clear_has_raw_y();
}
inline float Vision_DetectionRobot::raw_y() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.raw_y)
  return raw_y_;
}
inline void Vision_DetectionRobot::set_raw_y(float value) {
  set_has_raw_y();
  raw_y_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.raw_y)
}

// optional float raw_orientation = 13;
inline bool Vision_DetectionRobot::has_raw_orientation() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void Vision_DetectionRobot::set_has_raw_orientation() {
  _has_bits_[0] |= 0x00001000u;
}
inline void Vision_DetectionRobot::clear_has_raw_orientation() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void Vision_DetectionRobot::clear_raw_orientation() {
  raw_orientation_ = 0;
  clear_has_raw_orientation();
}
inline float Vision_DetectionRobot::raw_orientation() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.raw_orientation)
  return raw_orientation_;
}
inline void Vision_DetectionRobot::set_raw_orientation(float value) {
  set_has_raw_orientation();
  raw_orientation_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.raw_orientation)
}

// optional float raw_vel_x = 14;
inline bool Vision_DetectionRobot::has_raw_vel_x() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void Vision_DetectionRobot::set_has_raw_vel_x() {
  _has_bits_[0] |= 0x00002000u;
}
inline void Vision_DetectionRobot::clear_has_raw_vel_x() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void Vision_DetectionRobot::clear_raw_vel_x() {
  raw_vel_x_ = 0;
  clear_has_raw_vel_x();
}
inline float Vision_DetectionRobot::raw_vel_x() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.raw_vel_x)
  return raw_vel_x_;
}
inline void Vision_DetectionRobot::set_raw_vel_x(float value) {
  set_has_raw_vel_x();
  raw_vel_x_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.raw_vel_x)
}

// optional float raw_vel_y = 15;
inline bool Vision_DetectionRobot::has_raw_vel_y() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void Vision_DetectionRobot::set_has_raw_vel_y() {
  _has_bits_[0] |= 0x00004000u;
}
inline void Vision_DetectionRobot::clear_has_raw_vel_y() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void Vision_DetectionRobot::clear_raw_vel_y() {
  raw_vel_y_ = 0;
  clear_has_raw_vel_y();
}
inline float Vision_DetectionRobot::raw_vel_y() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.raw_vel_y)
  return raw_vel_y_;
}
inline void Vision_DetectionRobot::set_raw_vel_y(float value) {
  set_has_raw_vel_y();
  raw_vel_y_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.raw_vel_y)
}

// optional float raw_rotate_vel = 16;
inline bool Vision_DetectionRobot::has_raw_rotate_vel() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void Vision_DetectionRobot::set_has_raw_rotate_vel() {
  _has_bits_[0] |= 0x00008000u;
}
inline void Vision_DetectionRobot::clear_has_raw_rotate_vel() {
  _has_bits_[0] &= ~0x00008000u;
}
inline void Vision_DetectionRobot::clear_raw_rotate_vel() {
  raw_rotate_vel_ = 0;
  clear_has_raw_rotate_vel();
}
inline float Vision_DetectionRobot::raw_rotate_vel() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.raw_rotate_vel)
  return raw_rotate_vel_;
}
inline void Vision_DetectionRobot::set_raw_rotate_vel(float value) {
  set_has_raw_rotate_vel();
  raw_rotate_vel_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.raw_rotate_vel)
}

// required float confidence = 17;
inline bool Vision_DetectionRobot::has_confidence() const {
  return (_has_bits_[0] & 0x00010000u) != 0;
}
inline void Vision_DetectionRobot::set_has_confidence() {
  _has_bits_[0] |= 0x00010000u;
}
inline void Vision_DetectionRobot::clear_has_confidence() {
  _has_bits_[0] &= ~0x00010000u;
}
inline void Vision_DetectionRobot::clear_confidence() {
  confidence_ = 0;
  clear_has_confidence();
}
inline float Vision_DetectionRobot::confidence() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionRobot.confidence)
  return confidence_;
}
inline void Vision_DetectionRobot::set_confidence(float value) {
  set_has_confidence();
  confidence_ = value;
  // @@protoc_insertion_point(field_set:Vision_DetectionRobot.confidence)
}

// -------------------------------------------------------------------

// Vision_DetectionFrame

// required .Vision_DetectionBall balls = 1;
inline bool Vision_DetectionFrame::has_balls() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vision_DetectionFrame::set_has_balls() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vision_DetectionFrame::clear_has_balls() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vision_DetectionFrame::clear_balls() {
  if (balls_ != NULL) balls_->::Vision_DetectionBall::Clear();
  clear_has_balls();
}
inline const ::Vision_DetectionBall& Vision_DetectionFrame::balls() const {
  // @@protoc_insertion_point(field_get:Vision_DetectionFrame.balls)
  return balls_ != NULL ? *balls_
                         : *::Vision_DetectionBall::internal_default_instance();
}
inline ::Vision_DetectionBall* Vision_DetectionFrame::mutable_balls() {
  set_has_balls();
  if (balls_ == NULL) {
    balls_ = new ::Vision_DetectionBall;
  }
  // @@protoc_insertion_point(field_mutable:Vision_DetectionFrame.balls)
  return balls_;
}
inline ::Vision_DetectionBall* Vision_DetectionFrame::release_balls() {
  // @@protoc_insertion_point(field_release:Vision_DetectionFrame.balls)
  clear_has_balls();
  ::Vision_DetectionBall* temp = balls_;
  balls_ = NULL;
  return temp;
}
inline void Vision_DetectionFrame::set_allocated_balls(::Vision_DetectionBall* balls) {
  delete balls_;
  balls_ = balls;
  if (balls) {
    set_has_balls();
  } else {
    clear_has_balls();
  }
  // @@protoc_insertion_point(field_set_allocated:Vision_DetectionFrame.balls)
}

// repeated .Vision_DetectionRobot robots_yellow = 2;
inline int Vision_DetectionFrame::robots_yellow_size() const {
  return robots_yellow_.size();
}
inline void Vision_DetectionFrame::clear_robots_yellow() {
  robots_yellow_.Clear();
}
inline const ::Vision_DetectionRobot& Vision_DetectionFrame::robots_yellow(int index) const {
  // @@protoc_insertion_point(field_get:Vision_DetectionFrame.robots_yellow)
  return robots_yellow_.Get(index);
}
inline ::Vision_DetectionRobot* Vision_DetectionFrame::mutable_robots_yellow(int index) {
  // @@protoc_insertion_point(field_mutable:Vision_DetectionFrame.robots_yellow)
  return robots_yellow_.Mutable(index);
}
inline ::Vision_DetectionRobot* Vision_DetectionFrame::add_robots_yellow() {
  // @@protoc_insertion_point(field_add:Vision_DetectionFrame.robots_yellow)
  return robots_yellow_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Vision_DetectionRobot >*
Vision_DetectionFrame::mutable_robots_yellow() {
  // @@protoc_insertion_point(field_mutable_list:Vision_DetectionFrame.robots_yellow)
  return &robots_yellow_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Vision_DetectionRobot >&
Vision_DetectionFrame::robots_yellow() const {
  // @@protoc_insertion_point(field_list:Vision_DetectionFrame.robots_yellow)
  return robots_yellow_;
}

// repeated .Vision_DetectionRobot robots_blue = 3;
inline int Vision_DetectionFrame::robots_blue_size() const {
  return robots_blue_.size();
}
inline void Vision_DetectionFrame::clear_robots_blue() {
  robots_blue_.Clear();
}
inline const ::Vision_DetectionRobot& Vision_DetectionFrame::robots_blue(int index) const {
  // @@protoc_insertion_point(field_get:Vision_DetectionFrame.robots_blue)
  return robots_blue_.Get(index);
}
inline ::Vision_DetectionRobot* Vision_DetectionFrame::mutable_robots_blue(int index) {
  // @@protoc_insertion_point(field_mutable:Vision_DetectionFrame.robots_blue)
  return robots_blue_.Mutable(index);
}
inline ::Vision_DetectionRobot* Vision_DetectionFrame::add_robots_blue() {
  // @@protoc_insertion_point(field_add:Vision_DetectionFrame.robots_blue)
  return robots_blue_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Vision_DetectionRobot >*
Vision_DetectionFrame::mutable_robots_blue() {
  // @@protoc_insertion_point(field_mutable_list:Vision_DetectionFrame.robots_blue)
  return &robots_blue_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Vision_DetectionRobot >&
Vision_DetectionFrame::robots_blue() const {
  // @@protoc_insertion_point(field_list:Vision_DetectionFrame.robots_blue)
  return robots_blue_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_vision_5fdetection_2eproto__INCLUDED
