// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: referee.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "referee.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class SSL_Referee_TeamInfoDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SSL_Referee_TeamInfo> {
} _SSL_Referee_TeamInfo_default_instance_;
class SSL_Referee_PointDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SSL_Referee_Point> {
} _SSL_Referee_Point_default_instance_;
class SSL_RefereeDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SSL_Referee> {
} _SSL_Referee_default_instance_;

namespace protobuf_referee_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee_TeamInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee_TeamInfo, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee_TeamInfo, score_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee_TeamInfo, red_cards_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee_TeamInfo, yellow_card_times_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee_TeamInfo, yellow_cards_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee_TeamInfo, timeouts_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee_TeamInfo, timeout_time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee_TeamInfo, goalie_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee_Point, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee_Point, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee_Point, y_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee, packet_timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee, stage_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee, stage_time_left_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee, command_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee, command_counter_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee, command_timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee, yellow_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee, blue_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee, designated_position_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee, blueteamonpositivehalf_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_Referee, gameevent_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(SSL_Referee_TeamInfo)},
  { 13, -1, sizeof(SSL_Referee_Point)},
  { 20, -1, sizeof(SSL_Referee)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_SSL_Referee_TeamInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_SSL_Referee_Point_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_SSL_Referee_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "referee.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

}  // namespace

void TableStruct::Shutdown() {
  _SSL_Referee_TeamInfo_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _SSL_Referee_Point_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _SSL_Referee_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::protobuf_game_5fevent_2eproto::InitDefaults();
  _SSL_Referee_TeamInfo_default_instance_.DefaultConstruct();
  _SSL_Referee_Point_default_instance_.DefaultConstruct();
  _SSL_Referee_default_instance_.DefaultConstruct();
  _SSL_Referee_default_instance_.get_mutable()->yellow_ = const_cast< ::SSL_Referee_TeamInfo*>(
      ::SSL_Referee_TeamInfo::internal_default_instance());
  _SSL_Referee_default_instance_.get_mutable()->blue_ = const_cast< ::SSL_Referee_TeamInfo*>(
      ::SSL_Referee_TeamInfo::internal_default_instance());
  _SSL_Referee_default_instance_.get_mutable()->designated_position_ = const_cast< ::SSL_Referee_Point*>(
      ::SSL_Referee_Point::internal_default_instance());
  _SSL_Referee_default_instance_.get_mutable()->gameevent_ = const_cast< ::SSL_Referee_Game_Event*>(
      ::SSL_Referee_Game_Event::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\rreferee.proto\032\020game_event.proto\"\255\n\n\013SS"
      "L_Referee\022\030\n\020packet_timestamp\030\001 \001(\004\022!\n\005s"
      "tage\030\002 \001(\0162\022.SSL_Referee.Stage\022\027\n\017stage_"
      "time_left\030\003 \001(\021\022%\n\007command\030\004 \001(\0162\024.SSL_R"
      "eferee.Command\022\027\n\017command_counter\030\005 \001(\r\022"
      "\031\n\021command_timestamp\030\006 \001(\004\022%\n\006yellow\030\007 \001"
      "(\0132\025.SSL_Referee.TeamInfo\022#\n\004blue\030\010 \001(\0132"
      "\025.SSL_Referee.TeamInfo\022/\n\023designated_pos"
      "ition\030\t \001(\0132\022.SSL_Referee.Point\022\036\n\026blueT"
      "eamOnPositiveHalf\030\n \001(\010\022*\n\tgameEvent\030\013 \001"
      "(\0132\027.SSL_Referee_Game_Event\032\247\001\n\010TeamInfo"
      "\022\014\n\004name\030\001 \001(\t\022\r\n\005score\030\002 \001(\r\022\021\n\tred_car"
      "ds\030\003 \001(\r\022\035\n\021yellow_card_times\030\004 \003(\rB\002\020\001\022"
      "\024\n\014yellow_cards\030\005 \001(\r\022\020\n\010timeouts\030\006 \001(\r\022"
      "\024\n\014timeout_time\030\007 \001(\r\022\016\n\006goalie\030\010 \001(\r\032\035\n"
      "\005Point\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\"\321\002\n\005Stage\022\031"
      "\n\025NORMAL_FIRST_HALF_PRE\020\000\022\025\n\021NORMAL_FIRS"
      "T_HALF\020\001\022\024\n\020NORMAL_HALF_TIME\020\002\022\032\n\026NORMAL"
      "_SECOND_HALF_PRE\020\003\022\026\n\022NORMAL_SECOND_HALF"
      "\020\004\022\024\n\020EXTRA_TIME_BREAK\020\005\022\030\n\024EXTRA_FIRST_"
      "HALF_PRE\020\006\022\024\n\020EXTRA_FIRST_HALF\020\007\022\023\n\017EXTR"
      "A_HALF_TIME\020\010\022\031\n\025EXTRA_SECOND_HALF_PRE\020\t"
      "\022\025\n\021EXTRA_SECOND_HALF\020\n\022\032\n\026PENALTY_SHOOT"
      "OUT_BREAK\020\013\022\024\n\020PENALTY_SHOOTOUT\020\014\022\r\n\tPOS"
      "T_GAME\020\r\"\206\003\n\007Command\022\010\n\004HALT\020\000\022\010\n\004STOP\020\001"
      "\022\020\n\014NORMAL_START\020\002\022\017\n\013FORCE_START\020\003\022\032\n\026P"
      "REPARE_KICKOFF_YELLOW\020\004\022\030\n\024PREPARE_KICKO"
      "FF_BLUE\020\005\022\032\n\026PREPARE_PENALTY_YELLOW\020\006\022\030\n"
      "\024PREPARE_PENALTY_BLUE\020\007\022\026\n\022DIRECT_FREE_Y"
      "ELLOW\020\010\022\024\n\020DIRECT_FREE_BLUE\020\t\022\030\n\024INDIREC"
      "T_FREE_YELLOW\020\n\022\026\n\022INDIRECT_FREE_BLUE\020\013\022"
      "\022\n\016TIMEOUT_YELLOW\020\014\022\020\n\014TIMEOUT_BLUE\020\r\022\017\n"
      "\013GOAL_YELLOW\020\016\022\r\n\tGOAL_BLUE\020\017\022\031\n\025BALL_PL"
      "ACEMENT_YELLOW\020\020\022\027\n\023BALL_PLACEMENT_BLUE\020"
      "\021b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 1369);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "referee.proto", &protobuf_RegisterTypes);
  ::protobuf_game_5fevent_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_referee_2eproto

const ::google::protobuf::EnumDescriptor* SSL_Referee_Stage_descriptor() {
  protobuf_referee_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_referee_2eproto::file_level_enum_descriptors[0];
}
bool SSL_Referee_Stage_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const SSL_Referee_Stage SSL_Referee::NORMAL_FIRST_HALF_PRE;
const SSL_Referee_Stage SSL_Referee::NORMAL_FIRST_HALF;
const SSL_Referee_Stage SSL_Referee::NORMAL_HALF_TIME;
const SSL_Referee_Stage SSL_Referee::NORMAL_SECOND_HALF_PRE;
const SSL_Referee_Stage SSL_Referee::NORMAL_SECOND_HALF;
const SSL_Referee_Stage SSL_Referee::EXTRA_TIME_BREAK;
const SSL_Referee_Stage SSL_Referee::EXTRA_FIRST_HALF_PRE;
const SSL_Referee_Stage SSL_Referee::EXTRA_FIRST_HALF;
const SSL_Referee_Stage SSL_Referee::EXTRA_HALF_TIME;
const SSL_Referee_Stage SSL_Referee::EXTRA_SECOND_HALF_PRE;
const SSL_Referee_Stage SSL_Referee::EXTRA_SECOND_HALF;
const SSL_Referee_Stage SSL_Referee::PENALTY_SHOOTOUT_BREAK;
const SSL_Referee_Stage SSL_Referee::PENALTY_SHOOTOUT;
const SSL_Referee_Stage SSL_Referee::POST_GAME;
const SSL_Referee_Stage SSL_Referee::Stage_MIN;
const SSL_Referee_Stage SSL_Referee::Stage_MAX;
const int SSL_Referee::Stage_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* SSL_Referee_Command_descriptor() {
  protobuf_referee_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_referee_2eproto::file_level_enum_descriptors[1];
}
bool SSL_Referee_Command_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const SSL_Referee_Command SSL_Referee::HALT;
const SSL_Referee_Command SSL_Referee::STOP;
const SSL_Referee_Command SSL_Referee::NORMAL_START;
const SSL_Referee_Command SSL_Referee::FORCE_START;
const SSL_Referee_Command SSL_Referee::PREPARE_KICKOFF_YELLOW;
const SSL_Referee_Command SSL_Referee::PREPARE_KICKOFF_BLUE;
const SSL_Referee_Command SSL_Referee::PREPARE_PENALTY_YELLOW;
const SSL_Referee_Command SSL_Referee::PREPARE_PENALTY_BLUE;
const SSL_Referee_Command SSL_Referee::DIRECT_FREE_YELLOW;
const SSL_Referee_Command SSL_Referee::DIRECT_FREE_BLUE;
const SSL_Referee_Command SSL_Referee::INDIRECT_FREE_YELLOW;
const SSL_Referee_Command SSL_Referee::INDIRECT_FREE_BLUE;
const SSL_Referee_Command SSL_Referee::TIMEOUT_YELLOW;
const SSL_Referee_Command SSL_Referee::TIMEOUT_BLUE;
const SSL_Referee_Command SSL_Referee::GOAL_YELLOW;
const SSL_Referee_Command SSL_Referee::GOAL_BLUE;
const SSL_Referee_Command SSL_Referee::BALL_PLACEMENT_YELLOW;
const SSL_Referee_Command SSL_Referee::BALL_PLACEMENT_BLUE;
const SSL_Referee_Command SSL_Referee::Command_MIN;
const SSL_Referee_Command SSL_Referee::Command_MAX;
const int SSL_Referee::Command_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SSL_Referee_TeamInfo::kNameFieldNumber;
const int SSL_Referee_TeamInfo::kScoreFieldNumber;
const int SSL_Referee_TeamInfo::kRedCardsFieldNumber;
const int SSL_Referee_TeamInfo::kYellowCardTimesFieldNumber;
const int SSL_Referee_TeamInfo::kYellowCardsFieldNumber;
const int SSL_Referee_TeamInfo::kTimeoutsFieldNumber;
const int SSL_Referee_TeamInfo::kTimeoutTimeFieldNumber;
const int SSL_Referee_TeamInfo::kGoalieFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SSL_Referee_TeamInfo::SSL_Referee_TeamInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_referee_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:SSL_Referee.TeamInfo)
}
SSL_Referee_TeamInfo::SSL_Referee_TeamInfo(const SSL_Referee_TeamInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      yellow_card_times_(from.yellow_card_times_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  ::memcpy(&score_, &from.score_,
    reinterpret_cast<char*>(&goalie_) -
    reinterpret_cast<char*>(&score_) + sizeof(goalie_));
  // @@protoc_insertion_point(copy_constructor:SSL_Referee.TeamInfo)
}

void SSL_Referee_TeamInfo::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&score_, 0, reinterpret_cast<char*>(&goalie_) -
    reinterpret_cast<char*>(&score_) + sizeof(goalie_));
  _cached_size_ = 0;
}

SSL_Referee_TeamInfo::~SSL_Referee_TeamInfo() {
  // @@protoc_insertion_point(destructor:SSL_Referee.TeamInfo)
  SharedDtor();
}

void SSL_Referee_TeamInfo::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SSL_Referee_TeamInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SSL_Referee_TeamInfo::descriptor() {
  protobuf_referee_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_referee_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SSL_Referee_TeamInfo& SSL_Referee_TeamInfo::default_instance() {
  protobuf_referee_2eproto::InitDefaults();
  return *internal_default_instance();
}

SSL_Referee_TeamInfo* SSL_Referee_TeamInfo::New(::google::protobuf::Arena* arena) const {
  SSL_Referee_TeamInfo* n = new SSL_Referee_TeamInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SSL_Referee_TeamInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:SSL_Referee.TeamInfo)
  yellow_card_times_.Clear();
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&score_, 0, reinterpret_cast<char*>(&goalie_) -
    reinterpret_cast<char*>(&score_) + sizeof(goalie_));
}

bool SSL_Referee_TeamInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SSL_Referee.TeamInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "SSL_Referee.TeamInfo.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 score = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &score_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 red_cards = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &red_cards_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated uint32 yellow_card_times = 4 [packed = true];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_yellow_card_times())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(32u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 34u, input, this->mutable_yellow_card_times())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 yellow_cards = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &yellow_cards_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 timeouts = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &timeouts_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 timeout_time = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &timeout_time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 goalie = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &goalie_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SSL_Referee.TeamInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SSL_Referee.TeamInfo)
  return false;
#undef DO_
}

void SSL_Referee_TeamInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SSL_Referee.TeamInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "SSL_Referee.TeamInfo.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // uint32 score = 2;
  if (this->score() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->score(), output);
  }

  // uint32 red_cards = 3;
  if (this->red_cards() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->red_cards(), output);
  }

  // repeated uint32 yellow_card_times = 4 [packed = true];
  if (this->yellow_card_times_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(4, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_yellow_card_times_cached_byte_size_);
  }
  for (int i = 0, n = this->yellow_card_times_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->yellow_card_times(i), output);
  }

  // uint32 yellow_cards = 5;
  if (this->yellow_cards() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->yellow_cards(), output);
  }

  // uint32 timeouts = 6;
  if (this->timeouts() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->timeouts(), output);
  }

  // uint32 timeout_time = 7;
  if (this->timeout_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->timeout_time(), output);
  }

  // uint32 goalie = 8;
  if (this->goalie() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(8, this->goalie(), output);
  }

  // @@protoc_insertion_point(serialize_end:SSL_Referee.TeamInfo)
}

::google::protobuf::uint8* SSL_Referee_TeamInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SSL_Referee.TeamInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "SSL_Referee.TeamInfo.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // uint32 score = 2;
  if (this->score() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->score(), target);
  }

  // uint32 red_cards = 3;
  if (this->red_cards() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->red_cards(), target);
  }

  // repeated uint32 yellow_card_times = 4 [packed = true];
  if (this->yellow_card_times_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      4,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _yellow_card_times_cached_byte_size_, target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->yellow_card_times_, target);
  }

  // uint32 yellow_cards = 5;
  if (this->yellow_cards() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->yellow_cards(), target);
  }

  // uint32 timeouts = 6;
  if (this->timeouts() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->timeouts(), target);
  }

  // uint32 timeout_time = 7;
  if (this->timeout_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->timeout_time(), target);
  }

  // uint32 goalie = 8;
  if (this->goalie() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(8, this->goalie(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:SSL_Referee.TeamInfo)
  return target;
}

size_t SSL_Referee_TeamInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SSL_Referee.TeamInfo)
  size_t total_size = 0;

  // repeated uint32 yellow_card_times = 4 [packed = true];
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt32Size(this->yellow_card_times_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _yellow_card_times_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // uint32 score = 2;
  if (this->score() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->score());
  }

  // uint32 red_cards = 3;
  if (this->red_cards() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->red_cards());
  }

  // uint32 yellow_cards = 5;
  if (this->yellow_cards() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->yellow_cards());
  }

  // uint32 timeouts = 6;
  if (this->timeouts() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->timeouts());
  }

  // uint32 timeout_time = 7;
  if (this->timeout_time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->timeout_time());
  }

  // uint32 goalie = 8;
  if (this->goalie() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->goalie());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SSL_Referee_TeamInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SSL_Referee.TeamInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const SSL_Referee_TeamInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SSL_Referee_TeamInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SSL_Referee.TeamInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SSL_Referee.TeamInfo)
    MergeFrom(*source);
  }
}

void SSL_Referee_TeamInfo::MergeFrom(const SSL_Referee_TeamInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SSL_Referee.TeamInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  yellow_card_times_.MergeFrom(from.yellow_card_times_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.score() != 0) {
    set_score(from.score());
  }
  if (from.red_cards() != 0) {
    set_red_cards(from.red_cards());
  }
  if (from.yellow_cards() != 0) {
    set_yellow_cards(from.yellow_cards());
  }
  if (from.timeouts() != 0) {
    set_timeouts(from.timeouts());
  }
  if (from.timeout_time() != 0) {
    set_timeout_time(from.timeout_time());
  }
  if (from.goalie() != 0) {
    set_goalie(from.goalie());
  }
}

void SSL_Referee_TeamInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SSL_Referee.TeamInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SSL_Referee_TeamInfo::CopyFrom(const SSL_Referee_TeamInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SSL_Referee.TeamInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SSL_Referee_TeamInfo::IsInitialized() const {
  return true;
}

void SSL_Referee_TeamInfo::Swap(SSL_Referee_TeamInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SSL_Referee_TeamInfo::InternalSwap(SSL_Referee_TeamInfo* other) {
  yellow_card_times_.InternalSwap(&other->yellow_card_times_);
  name_.Swap(&other->name_);
  std::swap(score_, other->score_);
  std::swap(red_cards_, other->red_cards_);
  std::swap(yellow_cards_, other->yellow_cards_);
  std::swap(timeouts_, other->timeouts_);
  std::swap(timeout_time_, other->timeout_time_);
  std::swap(goalie_, other->goalie_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SSL_Referee_TeamInfo::GetMetadata() const {
  protobuf_referee_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_referee_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SSL_Referee_TeamInfo

// string name = 1;
void SSL_Referee_TeamInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& SSL_Referee_TeamInfo::name() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.TeamInfo.name)
  return name_.GetNoArena();
}
void SSL_Referee_TeamInfo::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SSL_Referee.TeamInfo.name)
}
#if LANG_CXX11
void SSL_Referee_TeamInfo::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:SSL_Referee.TeamInfo.name)
}
#endif
void SSL_Referee_TeamInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SSL_Referee.TeamInfo.name)
}
void SSL_Referee_TeamInfo::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SSL_Referee.TeamInfo.name)
}
::std::string* SSL_Referee_TeamInfo::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:SSL_Referee.TeamInfo.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* SSL_Referee_TeamInfo::release_name() {
  // @@protoc_insertion_point(field_release:SSL_Referee.TeamInfo.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SSL_Referee_TeamInfo::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:SSL_Referee.TeamInfo.name)
}

// uint32 score = 2;
void SSL_Referee_TeamInfo::clear_score() {
  score_ = 0u;
}
::google::protobuf::uint32 SSL_Referee_TeamInfo::score() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.TeamInfo.score)
  return score_;
}
void SSL_Referee_TeamInfo::set_score(::google::protobuf::uint32 value) {
  
  score_ = value;
  // @@protoc_insertion_point(field_set:SSL_Referee.TeamInfo.score)
}

// uint32 red_cards = 3;
void SSL_Referee_TeamInfo::clear_red_cards() {
  red_cards_ = 0u;
}
::google::protobuf::uint32 SSL_Referee_TeamInfo::red_cards() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.TeamInfo.red_cards)
  return red_cards_;
}
void SSL_Referee_TeamInfo::set_red_cards(::google::protobuf::uint32 value) {
  
  red_cards_ = value;
  // @@protoc_insertion_point(field_set:SSL_Referee.TeamInfo.red_cards)
}

// repeated uint32 yellow_card_times = 4 [packed = true];
int SSL_Referee_TeamInfo::yellow_card_times_size() const {
  return yellow_card_times_.size();
}
void SSL_Referee_TeamInfo::clear_yellow_card_times() {
  yellow_card_times_.Clear();
}
::google::protobuf::uint32 SSL_Referee_TeamInfo::yellow_card_times(int index) const {
  // @@protoc_insertion_point(field_get:SSL_Referee.TeamInfo.yellow_card_times)
  return yellow_card_times_.Get(index);
}
void SSL_Referee_TeamInfo::set_yellow_card_times(int index, ::google::protobuf::uint32 value) {
  yellow_card_times_.Set(index, value);
  // @@protoc_insertion_point(field_set:SSL_Referee.TeamInfo.yellow_card_times)
}
void SSL_Referee_TeamInfo::add_yellow_card_times(::google::protobuf::uint32 value) {
  yellow_card_times_.Add(value);
  // @@protoc_insertion_point(field_add:SSL_Referee.TeamInfo.yellow_card_times)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
SSL_Referee_TeamInfo::yellow_card_times() const {
  // @@protoc_insertion_point(field_list:SSL_Referee.TeamInfo.yellow_card_times)
  return yellow_card_times_;
}
::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
SSL_Referee_TeamInfo::mutable_yellow_card_times() {
  // @@protoc_insertion_point(field_mutable_list:SSL_Referee.TeamInfo.yellow_card_times)
  return &yellow_card_times_;
}

// uint32 yellow_cards = 5;
void SSL_Referee_TeamInfo::clear_yellow_cards() {
  yellow_cards_ = 0u;
}
::google::protobuf::uint32 SSL_Referee_TeamInfo::yellow_cards() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.TeamInfo.yellow_cards)
  return yellow_cards_;
}
void SSL_Referee_TeamInfo::set_yellow_cards(::google::protobuf::uint32 value) {
  
  yellow_cards_ = value;
  // @@protoc_insertion_point(field_set:SSL_Referee.TeamInfo.yellow_cards)
}

// uint32 timeouts = 6;
void SSL_Referee_TeamInfo::clear_timeouts() {
  timeouts_ = 0u;
}
::google::protobuf::uint32 SSL_Referee_TeamInfo::timeouts() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.TeamInfo.timeouts)
  return timeouts_;
}
void SSL_Referee_TeamInfo::set_timeouts(::google::protobuf::uint32 value) {
  
  timeouts_ = value;
  // @@protoc_insertion_point(field_set:SSL_Referee.TeamInfo.timeouts)
}

// uint32 timeout_time = 7;
void SSL_Referee_TeamInfo::clear_timeout_time() {
  timeout_time_ = 0u;
}
::google::protobuf::uint32 SSL_Referee_TeamInfo::timeout_time() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.TeamInfo.timeout_time)
  return timeout_time_;
}
void SSL_Referee_TeamInfo::set_timeout_time(::google::protobuf::uint32 value) {
  
  timeout_time_ = value;
  // @@protoc_insertion_point(field_set:SSL_Referee.TeamInfo.timeout_time)
}

// uint32 goalie = 8;
void SSL_Referee_TeamInfo::clear_goalie() {
  goalie_ = 0u;
}
::google::protobuf::uint32 SSL_Referee_TeamInfo::goalie() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.TeamInfo.goalie)
  return goalie_;
}
void SSL_Referee_TeamInfo::set_goalie(::google::protobuf::uint32 value) {
  
  goalie_ = value;
  // @@protoc_insertion_point(field_set:SSL_Referee.TeamInfo.goalie)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SSL_Referee_Point::kXFieldNumber;
const int SSL_Referee_Point::kYFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SSL_Referee_Point::SSL_Referee_Point()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_referee_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:SSL_Referee.Point)
}
SSL_Referee_Point::SSL_Referee_Point(const SSL_Referee_Point& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    reinterpret_cast<char*>(&y_) -
    reinterpret_cast<char*>(&x_) + sizeof(y_));
  // @@protoc_insertion_point(copy_constructor:SSL_Referee.Point)
}

void SSL_Referee_Point::SharedCtor() {
  ::memset(&x_, 0, reinterpret_cast<char*>(&y_) -
    reinterpret_cast<char*>(&x_) + sizeof(y_));
  _cached_size_ = 0;
}

SSL_Referee_Point::~SSL_Referee_Point() {
  // @@protoc_insertion_point(destructor:SSL_Referee.Point)
  SharedDtor();
}

void SSL_Referee_Point::SharedDtor() {
}

void SSL_Referee_Point::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SSL_Referee_Point::descriptor() {
  protobuf_referee_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_referee_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SSL_Referee_Point& SSL_Referee_Point::default_instance() {
  protobuf_referee_2eproto::InitDefaults();
  return *internal_default_instance();
}

SSL_Referee_Point* SSL_Referee_Point::New(::google::protobuf::Arena* arena) const {
  SSL_Referee_Point* n = new SSL_Referee_Point;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SSL_Referee_Point::Clear() {
// @@protoc_insertion_point(message_clear_start:SSL_Referee.Point)
  ::memset(&x_, 0, reinterpret_cast<char*>(&y_) -
    reinterpret_cast<char*>(&x_) + sizeof(y_));
}

bool SSL_Referee_Point::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SSL_Referee.Point)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SSL_Referee.Point)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SSL_Referee.Point)
  return false;
#undef DO_
}

void SSL_Referee_Point::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SSL_Referee.Point)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->x(), output);
  }

  // float y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->y(), output);
  }

  // @@protoc_insertion_point(serialize_end:SSL_Referee.Point)
}

::google::protobuf::uint8* SSL_Referee_Point::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SSL_Referee.Point)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->x(), target);
  }

  // float y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->y(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:SSL_Referee.Point)
  return target;
}

size_t SSL_Referee_Point::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SSL_Referee.Point)
  size_t total_size = 0;

  // float x = 1;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // float y = 2;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SSL_Referee_Point::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SSL_Referee.Point)
  GOOGLE_DCHECK_NE(&from, this);
  const SSL_Referee_Point* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SSL_Referee_Point>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SSL_Referee.Point)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SSL_Referee.Point)
    MergeFrom(*source);
  }
}

void SSL_Referee_Point::MergeFrom(const SSL_Referee_Point& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SSL_Referee.Point)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
}

void SSL_Referee_Point::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SSL_Referee.Point)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SSL_Referee_Point::CopyFrom(const SSL_Referee_Point& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SSL_Referee.Point)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SSL_Referee_Point::IsInitialized() const {
  return true;
}

void SSL_Referee_Point::Swap(SSL_Referee_Point* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SSL_Referee_Point::InternalSwap(SSL_Referee_Point* other) {
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SSL_Referee_Point::GetMetadata() const {
  protobuf_referee_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_referee_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SSL_Referee_Point

// float x = 1;
void SSL_Referee_Point::clear_x() {
  x_ = 0;
}
float SSL_Referee_Point::x() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.Point.x)
  return x_;
}
void SSL_Referee_Point::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:SSL_Referee.Point.x)
}

// float y = 2;
void SSL_Referee_Point::clear_y() {
  y_ = 0;
}
float SSL_Referee_Point::y() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.Point.y)
  return y_;
}
void SSL_Referee_Point::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:SSL_Referee.Point.y)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SSL_Referee::kPacketTimestampFieldNumber;
const int SSL_Referee::kStageFieldNumber;
const int SSL_Referee::kStageTimeLeftFieldNumber;
const int SSL_Referee::kCommandFieldNumber;
const int SSL_Referee::kCommandCounterFieldNumber;
const int SSL_Referee::kCommandTimestampFieldNumber;
const int SSL_Referee::kYellowFieldNumber;
const int SSL_Referee::kBlueFieldNumber;
const int SSL_Referee::kDesignatedPositionFieldNumber;
const int SSL_Referee::kBlueTeamOnPositiveHalfFieldNumber;
const int SSL_Referee::kGameEventFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SSL_Referee::SSL_Referee()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_referee_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:SSL_Referee)
}
SSL_Referee::SSL_Referee(const SSL_Referee& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_yellow()) {
    yellow_ = new ::SSL_Referee_TeamInfo(*from.yellow_);
  } else {
    yellow_ = NULL;
  }
  if (from.has_blue()) {
    blue_ = new ::SSL_Referee_TeamInfo(*from.blue_);
  } else {
    blue_ = NULL;
  }
  if (from.has_designated_position()) {
    designated_position_ = new ::SSL_Referee_Point(*from.designated_position_);
  } else {
    designated_position_ = NULL;
  }
  if (from.has_gameevent()) {
    gameevent_ = new ::SSL_Referee_Game_Event(*from.gameevent_);
  } else {
    gameevent_ = NULL;
  }
  ::memcpy(&packet_timestamp_, &from.packet_timestamp_,
    reinterpret_cast<char*>(&blueteamonpositivehalf_) -
    reinterpret_cast<char*>(&packet_timestamp_) + sizeof(blueteamonpositivehalf_));
  // @@protoc_insertion_point(copy_constructor:SSL_Referee)
}

void SSL_Referee::SharedCtor() {
  ::memset(&yellow_, 0, reinterpret_cast<char*>(&blueteamonpositivehalf_) -
    reinterpret_cast<char*>(&yellow_) + sizeof(blueteamonpositivehalf_));
  _cached_size_ = 0;
}

SSL_Referee::~SSL_Referee() {
  // @@protoc_insertion_point(destructor:SSL_Referee)
  SharedDtor();
}

void SSL_Referee::SharedDtor() {
  if (this != internal_default_instance()) {
    delete yellow_;
  }
  if (this != internal_default_instance()) {
    delete blue_;
  }
  if (this != internal_default_instance()) {
    delete designated_position_;
  }
  if (this != internal_default_instance()) {
    delete gameevent_;
  }
}

void SSL_Referee::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SSL_Referee::descriptor() {
  protobuf_referee_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_referee_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SSL_Referee& SSL_Referee::default_instance() {
  protobuf_referee_2eproto::InitDefaults();
  return *internal_default_instance();
}

SSL_Referee* SSL_Referee::New(::google::protobuf::Arena* arena) const {
  SSL_Referee* n = new SSL_Referee;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SSL_Referee::Clear() {
// @@protoc_insertion_point(message_clear_start:SSL_Referee)
  if (GetArenaNoVirtual() == NULL && yellow_ != NULL) {
    delete yellow_;
  }
  yellow_ = NULL;
  if (GetArenaNoVirtual() == NULL && blue_ != NULL) {
    delete blue_;
  }
  blue_ = NULL;
  if (GetArenaNoVirtual() == NULL && designated_position_ != NULL) {
    delete designated_position_;
  }
  designated_position_ = NULL;
  if (GetArenaNoVirtual() == NULL && gameevent_ != NULL) {
    delete gameevent_;
  }
  gameevent_ = NULL;
  ::memset(&packet_timestamp_, 0, reinterpret_cast<char*>(&blueteamonpositivehalf_) -
    reinterpret_cast<char*>(&packet_timestamp_) + sizeof(blueteamonpositivehalf_));
}

bool SSL_Referee::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SSL_Referee)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 packet_timestamp = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &packet_timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .SSL_Referee.Stage stage = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_stage(static_cast< ::SSL_Referee_Stage >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 stage_time_left = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &stage_time_left_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .SSL_Referee.Command command = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_command(static_cast< ::SSL_Referee_Command >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 command_counter = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &command_counter_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 command_timestamp = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &command_timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .SSL_Referee.TeamInfo yellow = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_yellow()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .SSL_Referee.TeamInfo blue = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_blue()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .SSL_Referee.Point designated_position = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_designated_position()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool blueTeamOnPositiveHalf = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &blueteamonpositivehalf_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .SSL_Referee_Game_Event gameEvent = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_gameevent()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SSL_Referee)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SSL_Referee)
  return false;
#undef DO_
}

void SSL_Referee::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SSL_Referee)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 packet_timestamp = 1;
  if (this->packet_timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->packet_timestamp(), output);
  }

  // .SSL_Referee.Stage stage = 2;
  if (this->stage() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->stage(), output);
  }

  // sint32 stage_time_left = 3;
  if (this->stage_time_left() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(3, this->stage_time_left(), output);
  }

  // .SSL_Referee.Command command = 4;
  if (this->command() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->command(), output);
  }

  // uint32 command_counter = 5;
  if (this->command_counter() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->command_counter(), output);
  }

  // uint64 command_timestamp = 6;
  if (this->command_timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(6, this->command_timestamp(), output);
  }

  // .SSL_Referee.TeamInfo yellow = 7;
  if (this->has_yellow()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, *this->yellow_, output);
  }

  // .SSL_Referee.TeamInfo blue = 8;
  if (this->has_blue()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8, *this->blue_, output);
  }

  // .SSL_Referee.Point designated_position = 9;
  if (this->has_designated_position()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      9, *this->designated_position_, output);
  }

  // bool blueTeamOnPositiveHalf = 10;
  if (this->blueteamonpositivehalf() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(10, this->blueteamonpositivehalf(), output);
  }

  // .SSL_Referee_Game_Event gameEvent = 11;
  if (this->has_gameevent()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, *this->gameevent_, output);
  }

  // @@protoc_insertion_point(serialize_end:SSL_Referee)
}

::google::protobuf::uint8* SSL_Referee::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SSL_Referee)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 packet_timestamp = 1;
  if (this->packet_timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->packet_timestamp(), target);
  }

  // .SSL_Referee.Stage stage = 2;
  if (this->stage() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->stage(), target);
  }

  // sint32 stage_time_left = 3;
  if (this->stage_time_left() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(3, this->stage_time_left(), target);
  }

  // .SSL_Referee.Command command = 4;
  if (this->command() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->command(), target);
  }

  // uint32 command_counter = 5;
  if (this->command_counter() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->command_counter(), target);
  }

  // uint64 command_timestamp = 6;
  if (this->command_timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(6, this->command_timestamp(), target);
  }

  // .SSL_Referee.TeamInfo yellow = 7;
  if (this->has_yellow()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        7, *this->yellow_, deterministic, target);
  }

  // .SSL_Referee.TeamInfo blue = 8;
  if (this->has_blue()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        8, *this->blue_, deterministic, target);
  }

  // .SSL_Referee.Point designated_position = 9;
  if (this->has_designated_position()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        9, *this->designated_position_, deterministic, target);
  }

  // bool blueTeamOnPositiveHalf = 10;
  if (this->blueteamonpositivehalf() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(10, this->blueteamonpositivehalf(), target);
  }

  // .SSL_Referee_Game_Event gameEvent = 11;
  if (this->has_gameevent()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        11, *this->gameevent_, deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:SSL_Referee)
  return target;
}

size_t SSL_Referee::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SSL_Referee)
  size_t total_size = 0;

  // .SSL_Referee.TeamInfo yellow = 7;
  if (this->has_yellow()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->yellow_);
  }

  // .SSL_Referee.TeamInfo blue = 8;
  if (this->has_blue()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->blue_);
  }

  // .SSL_Referee.Point designated_position = 9;
  if (this->has_designated_position()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->designated_position_);
  }

  // .SSL_Referee_Game_Event gameEvent = 11;
  if (this->has_gameevent()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->gameevent_);
  }

  // uint64 packet_timestamp = 1;
  if (this->packet_timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->packet_timestamp());
  }

  // .SSL_Referee.Stage stage = 2;
  if (this->stage() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->stage());
  }

  // sint32 stage_time_left = 3;
  if (this->stage_time_left() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->stage_time_left());
  }

  // .SSL_Referee.Command command = 4;
  if (this->command() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->command());
  }

  // uint32 command_counter = 5;
  if (this->command_counter() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->command_counter());
  }

  // uint64 command_timestamp = 6;
  if (this->command_timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->command_timestamp());
  }

  // bool blueTeamOnPositiveHalf = 10;
  if (this->blueteamonpositivehalf() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SSL_Referee::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SSL_Referee)
  GOOGLE_DCHECK_NE(&from, this);
  const SSL_Referee* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SSL_Referee>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SSL_Referee)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SSL_Referee)
    MergeFrom(*source);
  }
}

void SSL_Referee::MergeFrom(const SSL_Referee& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SSL_Referee)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_yellow()) {
    mutable_yellow()->::SSL_Referee_TeamInfo::MergeFrom(from.yellow());
  }
  if (from.has_blue()) {
    mutable_blue()->::SSL_Referee_TeamInfo::MergeFrom(from.blue());
  }
  if (from.has_designated_position()) {
    mutable_designated_position()->::SSL_Referee_Point::MergeFrom(from.designated_position());
  }
  if (from.has_gameevent()) {
    mutable_gameevent()->::SSL_Referee_Game_Event::MergeFrom(from.gameevent());
  }
  if (from.packet_timestamp() != 0) {
    set_packet_timestamp(from.packet_timestamp());
  }
  if (from.stage() != 0) {
    set_stage(from.stage());
  }
  if (from.stage_time_left() != 0) {
    set_stage_time_left(from.stage_time_left());
  }
  if (from.command() != 0) {
    set_command(from.command());
  }
  if (from.command_counter() != 0) {
    set_command_counter(from.command_counter());
  }
  if (from.command_timestamp() != 0) {
    set_command_timestamp(from.command_timestamp());
  }
  if (from.blueteamonpositivehalf() != 0) {
    set_blueteamonpositivehalf(from.blueteamonpositivehalf());
  }
}

void SSL_Referee::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SSL_Referee)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SSL_Referee::CopyFrom(const SSL_Referee& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SSL_Referee)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SSL_Referee::IsInitialized() const {
  return true;
}

void SSL_Referee::Swap(SSL_Referee* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SSL_Referee::InternalSwap(SSL_Referee* other) {
  std::swap(yellow_, other->yellow_);
  std::swap(blue_, other->blue_);
  std::swap(designated_position_, other->designated_position_);
  std::swap(gameevent_, other->gameevent_);
  std::swap(packet_timestamp_, other->packet_timestamp_);
  std::swap(stage_, other->stage_);
  std::swap(stage_time_left_, other->stage_time_left_);
  std::swap(command_, other->command_);
  std::swap(command_counter_, other->command_counter_);
  std::swap(command_timestamp_, other->command_timestamp_);
  std::swap(blueteamonpositivehalf_, other->blueteamonpositivehalf_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SSL_Referee::GetMetadata() const {
  protobuf_referee_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_referee_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SSL_Referee

// uint64 packet_timestamp = 1;
void SSL_Referee::clear_packet_timestamp() {
  packet_timestamp_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 SSL_Referee::packet_timestamp() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.packet_timestamp)
  return packet_timestamp_;
}
void SSL_Referee::set_packet_timestamp(::google::protobuf::uint64 value) {
  
  packet_timestamp_ = value;
  // @@protoc_insertion_point(field_set:SSL_Referee.packet_timestamp)
}

// .SSL_Referee.Stage stage = 2;
void SSL_Referee::clear_stage() {
  stage_ = 0;
}
::SSL_Referee_Stage SSL_Referee::stage() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.stage)
  return static_cast< ::SSL_Referee_Stage >(stage_);
}
void SSL_Referee::set_stage(::SSL_Referee_Stage value) {
  
  stage_ = value;
  // @@protoc_insertion_point(field_set:SSL_Referee.stage)
}

// sint32 stage_time_left = 3;
void SSL_Referee::clear_stage_time_left() {
  stage_time_left_ = 0;
}
::google::protobuf::int32 SSL_Referee::stage_time_left() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.stage_time_left)
  return stage_time_left_;
}
void SSL_Referee::set_stage_time_left(::google::protobuf::int32 value) {
  
  stage_time_left_ = value;
  // @@protoc_insertion_point(field_set:SSL_Referee.stage_time_left)
}

// .SSL_Referee.Command command = 4;
void SSL_Referee::clear_command() {
  command_ = 0;
}
::SSL_Referee_Command SSL_Referee::command() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.command)
  return static_cast< ::SSL_Referee_Command >(command_);
}
void SSL_Referee::set_command(::SSL_Referee_Command value) {
  
  command_ = value;
  // @@protoc_insertion_point(field_set:SSL_Referee.command)
}

// uint32 command_counter = 5;
void SSL_Referee::clear_command_counter() {
  command_counter_ = 0u;
}
::google::protobuf::uint32 SSL_Referee::command_counter() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.command_counter)
  return command_counter_;
}
void SSL_Referee::set_command_counter(::google::protobuf::uint32 value) {
  
  command_counter_ = value;
  // @@protoc_insertion_point(field_set:SSL_Referee.command_counter)
}

// uint64 command_timestamp = 6;
void SSL_Referee::clear_command_timestamp() {
  command_timestamp_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 SSL_Referee::command_timestamp() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.command_timestamp)
  return command_timestamp_;
}
void SSL_Referee::set_command_timestamp(::google::protobuf::uint64 value) {
  
  command_timestamp_ = value;
  // @@protoc_insertion_point(field_set:SSL_Referee.command_timestamp)
}

// .SSL_Referee.TeamInfo yellow = 7;
bool SSL_Referee::has_yellow() const {
  return this != internal_default_instance() && yellow_ != NULL;
}
void SSL_Referee::clear_yellow() {
  if (GetArenaNoVirtual() == NULL && yellow_ != NULL) delete yellow_;
  yellow_ = NULL;
}
const ::SSL_Referee_TeamInfo& SSL_Referee::yellow() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.yellow)
  return yellow_ != NULL ? *yellow_
                         : *::SSL_Referee_TeamInfo::internal_default_instance();
}
::SSL_Referee_TeamInfo* SSL_Referee::mutable_yellow() {
  
  if (yellow_ == NULL) {
    yellow_ = new ::SSL_Referee_TeamInfo;
  }
  // @@protoc_insertion_point(field_mutable:SSL_Referee.yellow)
  return yellow_;
}
::SSL_Referee_TeamInfo* SSL_Referee::release_yellow() {
  // @@protoc_insertion_point(field_release:SSL_Referee.yellow)
  
  ::SSL_Referee_TeamInfo* temp = yellow_;
  yellow_ = NULL;
  return temp;
}
void SSL_Referee::set_allocated_yellow(::SSL_Referee_TeamInfo* yellow) {
  delete yellow_;
  yellow_ = yellow;
  if (yellow) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:SSL_Referee.yellow)
}

// .SSL_Referee.TeamInfo blue = 8;
bool SSL_Referee::has_blue() const {
  return this != internal_default_instance() && blue_ != NULL;
}
void SSL_Referee::clear_blue() {
  if (GetArenaNoVirtual() == NULL && blue_ != NULL) delete blue_;
  blue_ = NULL;
}
const ::SSL_Referee_TeamInfo& SSL_Referee::blue() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.blue)
  return blue_ != NULL ? *blue_
                         : *::SSL_Referee_TeamInfo::internal_default_instance();
}
::SSL_Referee_TeamInfo* SSL_Referee::mutable_blue() {
  
  if (blue_ == NULL) {
    blue_ = new ::SSL_Referee_TeamInfo;
  }
  // @@protoc_insertion_point(field_mutable:SSL_Referee.blue)
  return blue_;
}
::SSL_Referee_TeamInfo* SSL_Referee::release_blue() {
  // @@protoc_insertion_point(field_release:SSL_Referee.blue)
  
  ::SSL_Referee_TeamInfo* temp = blue_;
  blue_ = NULL;
  return temp;
}
void SSL_Referee::set_allocated_blue(::SSL_Referee_TeamInfo* blue) {
  delete blue_;
  blue_ = blue;
  if (blue) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:SSL_Referee.blue)
}

// .SSL_Referee.Point designated_position = 9;
bool SSL_Referee::has_designated_position() const {
  return this != internal_default_instance() && designated_position_ != NULL;
}
void SSL_Referee::clear_designated_position() {
  if (GetArenaNoVirtual() == NULL && designated_position_ != NULL) delete designated_position_;
  designated_position_ = NULL;
}
const ::SSL_Referee_Point& SSL_Referee::designated_position() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.designated_position)
  return designated_position_ != NULL ? *designated_position_
                         : *::SSL_Referee_Point::internal_default_instance();
}
::SSL_Referee_Point* SSL_Referee::mutable_designated_position() {
  
  if (designated_position_ == NULL) {
    designated_position_ = new ::SSL_Referee_Point;
  }
  // @@protoc_insertion_point(field_mutable:SSL_Referee.designated_position)
  return designated_position_;
}
::SSL_Referee_Point* SSL_Referee::release_designated_position() {
  // @@protoc_insertion_point(field_release:SSL_Referee.designated_position)
  
  ::SSL_Referee_Point* temp = designated_position_;
  designated_position_ = NULL;
  return temp;
}
void SSL_Referee::set_allocated_designated_position(::SSL_Referee_Point* designated_position) {
  delete designated_position_;
  designated_position_ = designated_position;
  if (designated_position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:SSL_Referee.designated_position)
}

// bool blueTeamOnPositiveHalf = 10;
void SSL_Referee::clear_blueteamonpositivehalf() {
  blueteamonpositivehalf_ = false;
}
bool SSL_Referee::blueteamonpositivehalf() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.blueTeamOnPositiveHalf)
  return blueteamonpositivehalf_;
}
void SSL_Referee::set_blueteamonpositivehalf(bool value) {
  
  blueteamonpositivehalf_ = value;
  // @@protoc_insertion_point(field_set:SSL_Referee.blueTeamOnPositiveHalf)
}

// .SSL_Referee_Game_Event gameEvent = 11;
bool SSL_Referee::has_gameevent() const {
  return this != internal_default_instance() && gameevent_ != NULL;
}
void SSL_Referee::clear_gameevent() {
  if (GetArenaNoVirtual() == NULL && gameevent_ != NULL) delete gameevent_;
  gameevent_ = NULL;
}
const ::SSL_Referee_Game_Event& SSL_Referee::gameevent() const {
  // @@protoc_insertion_point(field_get:SSL_Referee.gameEvent)
  return gameevent_ != NULL ? *gameevent_
                         : *::SSL_Referee_Game_Event::internal_default_instance();
}
::SSL_Referee_Game_Event* SSL_Referee::mutable_gameevent() {
  
  if (gameevent_ == NULL) {
    gameevent_ = new ::SSL_Referee_Game_Event;
  }
  // @@protoc_insertion_point(field_mutable:SSL_Referee.gameEvent)
  return gameevent_;
}
::SSL_Referee_Game_Event* SSL_Referee::release_gameevent() {
  // @@protoc_insertion_point(field_release:SSL_Referee.gameEvent)
  
  ::SSL_Referee_Game_Event* temp = gameevent_;
  gameevent_ = NULL;
  return temp;
}
void SSL_Referee::set_allocated_gameevent(::SSL_Referee_Game_Event* gameevent) {
  delete gameevent_;
  gameevent_ = gameevent;
  if (gameevent) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:SSL_Referee.gameEvent)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
